ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /odom
    odom0_config: [
      true, true, false,        # x, y, z true true false
      false, false, true,       # roll, pitch, yaw
      true, false, false,        # vx, vy, vz
      false, false, false,       # roll rate, pitch rate, yaw rate
      false, false, false       # ax, ay, az
    ]
    #  odom1: /cmd_odom
    # odom1_config: [
    #  false, false, false,        # x, y, z
    #  false, false, false,       # roll, pitch, yaw
    #  false, false, false,        # vx, vy, vz
    #  false, false, false,       # roll rate, pitch rate, yaw rate
    #  false, false, false       # ax, ay, az
    # ]
 
    #  imu1: /imu
    #  imu1_config: [
      #  false, false, false,
      # false, false, false,    # orientation not provided
      # false, false, false,
      # false, false, false,     # angular velocity
      # false, false, false      # linear acceleration
      # ]
      # imu1_differential: false
      # imu1_remove_gravitational_acceleration: true

    #  imu0: /imu/yaw
    #  imu0_config: [
    #  false, false, false,
    #  false, false, false,     # only yaw
    #  false, false, false,
    #  false, false, false,
    #  false, false, false
    #]
    # imu0_differential: false
    #imu0_remove_gravitational_acceleration: true

    # use_sim_time: false
